Removed some UCSLS specific requirements

diff --git a/base/Dockerfile b/base/Dockerfile
--- a/base/Dockerfile
+++ b/base/Dockerfile
@@ -6,7 +6,7 @@ ARG FROM_REG
 ARG FROM_IMAGE
 ARG FROM_TAG
 
-FROM ${FROM_REG}${FROM_IMAGE}${FROM_TAG}
+FROM ${FROM_REG}${FROM_IMAGE}${FROM_TAG} AS stage-one
 
 LABEL maintainer="Open Education <opeffort@gmail.com>"
 
@@ -30,12 +30,13 @@ SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 # change file permissions, etc.
 
 # install linux packages that we require for systems classes
-USER root
 
-RUN dpkg --add-architecture i386 && \
-    apt-get -y update --fix-missing && \
-    apt-get -y install ${ADDITIONAL_DISTRO_PACKAGES} && \
-    apt-get clean && rm -rf /var/lib/apt/lists/*
+# USER root
+
+# RUN dpkg --add-architecture i386 && \
+#    apt-get -y update --fix-missing && \
+#    apt-get -y install ${ADDITIONAL_DISTRO_PACKAGES} && \
+#    apt-get clean && rm -rf /var/lib/apt/lists/*
 
 # Now that distro packages are installed lets install the python packages we want
 # This was inspired by
@@ -52,7 +53,8 @@ RUN mamba install --quiet --yes \
     fix-permissions "/home/${NB_USER}"
 
 # Conda 4.13.0 has some strange dependency that pulling code from the recent head, causing the mamba clean fail
-RUN conda install conda=4.14.0 --yes
+# minimal-notebook:2022-08-23 has conda 4.14.0, so we don't need to upgrade to that version
+# RUN conda install conda=4.14.0 --yes
     
 # Install Python 3 packages
 # Install pip packages (things we could not get via mamba) as well
@@ -71,92 +73,143 @@ RUN MPLBACKEND=Agg python -c "import matplotlib.pyplot" && \
     fix-permissions "/home/${NB_USER}"
 
 # enable extensions
-RUN for ext in ${JUPYTER_ENABLE_EXTENSIONS} ; do \
-   jupyter nbextension enable "$ext" ; \
-   done && \
-   fix-permissions "${CONDA_DIR}" && \
-   fix-permissions "/home/${NB_USER}"
+# RUN for ext in ${JUPYTER_ENABLE_EXTENSIONS} ; do \
+#    jupyter nbextension enable "$ext" ; \
+#    done && \
+#    fix-permissions "${CONDA_DIR}" && \
+#    fix-permissions "/home/${NB_USER}"
 
 # disable extensions -- disabling core extensions can be really useful for customizing
 #                       jupyterlab user experience
-RUN for ext in ${JUPYTER_DISABLE_EXTENSIONS} ; do \
-   jupyter labextension disable "$ext" ; \
-   done && \
-   fix-permissions "${CONDA_DIR}" && \
-   fix-permissions "/home/${NB_USER}"
+# RUN for ext in ${JUPYTER_DISABLE_EXTENSIONS} ; do \
+#    jupyter labextension disable "$ext" ; \
+#    done && \
+#    fix-permissions "${CONDA_DIR}" && \
+#    fix-permissions "/home/${NB_USER}"
 
 USER root
 
 # get and build gdb form source so that we have a current version >10 that support more advanced tui functionality 
-RUN if [[ -n "${GDB_BUILD_SRC}" ]] ; then \
-      cd /tmp && \
-      wget http://ftp.gnu.org/gnu/gdb/${GDB_BUILD_SRC}.tar.gz && \
-      tar -zxf ${GDB_BUILD_SRC}.tar.gz && \
-      cd ${GDB_BUILD_SRC} && \
-      ./configure --prefix /usr/local --enable-tui=yes && \
-      make -j 4 && make install && \
-      cd /tmp && \
-      rm -rf ${GDB_BUILD_SRC} && rm ${GDB_BUILD_SRC}.tar.gz ; \
-    fi 
+# RUN if [[ -n "${GDB_BUILD_SRC}" ]] ; then \
+#       cd /tmp && \
+#       wget http://ftp.gnu.org/gnu/gdb/${GDB_BUILD_SRC}.tar.gz && \
+#       tar -zxf ${GDB_BUILD_SRC}.tar.gz && \
+#       cd ${GDB_BUILD_SRC} && \
+#       ./configure --prefix /usr/local --enable-tui=yes && \
+#       make -j 4 && make install && \
+#       cd /tmp && \
+#       rm -rf ${GDB_BUILD_SRC} && rm ${GDB_BUILD_SRC}.tar.gz ; \
+#     fi 
 
 # copy overrides.json
 COPY settings ${CONDA_DIR}/share/jupyter/lab/settings
 RUN fix-permissions ${CONDA_DIR}/share/jupyter/lab/settings
 
-USER root
-
 # we want the container to feel more like a fully fledged system so we are pulling the trigger and unminimizing it
-RUN [[ $UNMIN == "yes" ]] &&  yes | unminimize || true
+# RUN [[ $UNMIN == "yes" ]] &&  yes | unminimize || true
 
 
 # Add ARM development environtment
-COPY aarch64vm /home/aarch64vm
-RUN fix-permissions /home/aarch64vm
+# COPY aarch64vm /home/aarch64vm
+# RUN fix-permissions /home/aarch64vm
 
 # final bits of cleanup 
-RUN touch /home/${NB_USER}/.hushlogin && \
-# use a short prompt to improve default behaviour in presentations
-    echo "export PS1='\$ '" >> /home/${NB_USER}/.bashrc && \
-# work around bug when term is xterm and emacs runs in xterm.js -- causes escape characters in file    
-    echo "export TERM=linux" >> /home/${NB_USER}/.bashrc && \
-# finally remove default working directory from joyvan home
-    rmdir /home/${NB_USER}/work && \
+# RUN touch /home/${NB_USER}/.hushlogin && \
+# # use a short prompt to improve default behaviour in presentations
+#     echo "export PS1='\$ '" >> /home/${NB_USER}/.bashrc && \
+# # work around bug when term is xterm and emacs runs in xterm.js -- causes escape characters in file    
+#     echo "export TERM=linux" >> /home/${NB_USER}/.bashrc && \
+# # finally remove default working directory from joyvan home
+#     rmdir /home/${NB_USER}/work && \
+#     fix-permissions "/home/${NB_USER}"
+
+## Dockerfile for constructing the base Open Education Effort (OPE)
+## container.  This container contains everything required for authoring OPE courses
+## Well is should anyway ;-)
+
+ARG FROM_REG
+ARG FROM_IMAGE
+ARG FROM_TAG
+
+FROM ${FROM_REG}${FROM_IMAGE}${FROM_TAG} AS stage-two
+#COPY --from=stage-one /opt/conda/lib/python3.10/site-packages/ /opt/conda/lib/python3.10/site-packages/ 
+#COPY --from=stage-one /opt/conda/lib/ /opt/conda/lib/
+COPY --from=stage-one /opt/conda /opt/conda
+COPY --from=stage-one /usr/local/bin /usr/local/bin
+COPY --from=stage-one /usr/lib /usr/lib
+
+#COPY --from=stage-one /home/RISE /home/RISE
+
+LABEL maintainer="Open Education <opeffort@gmail.com>"
+
+ARG JUPYTER_ENABLE_EXTENSIONS
+ARG JUPYTER_DISABLE_EXTENSIONS
+ARG UNMIN
+# ARG ADDITIONAL_DISTRO_PACKAGES
+
+# Fix: https://github.com/hadolint/hadolint/wiki/DL4006
+# Fix: https://github.com/koalaman/shellcheck/wiki/SC3014
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+USER ${NB_UID}
+
+# RUN for ext in ${JUPYTER_ENABLE_EXTENSIONS} ; do \
+#    jupyter nbextension enable "$ext" ; \
+#    done
+
+# disable extensions -- disabling core extensions can be really useful for customizing
+#                       jupyterlab user experience
+RUN for ext in ${JUPYTER_DISABLE_EXTENSIONS} ; do \
+   jupyter labextension disable "$ext" ; \
+   done
+
+# Import matplotlib the first time to build the font cache.
+ENV XDG_CACHE_HOME="/home/${NB_USER}/.cache/"
+
+RUN MPLBACKEND=Agg python -c "import matplotlib.pyplot" && \
     fix-permissions "/home/${NB_USER}"
 
-# adding our custom OPE version of RISE for lab -- remove once main RISE is fixed
-RUN  wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg 2> /dev/null | sudo apt-key add - && \
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
- sudo apt-get update -y && \
- sudo apt-get install yarn -y && \
- mkdir /home/RISE && \
- chown jovyan /home/RISE && \
- fix-permissions /home/RISE
+# copy overrides.json
+COPY settings ${CONDA_DIR}/share/jupyter/lab/settings
 
-USER $NB_USER
-# swtiched back to Yiqin's branch to pickup fixes for toggling controls and notes
-RUN  git clone https://github.com/OPEFFORT/RISE.git /home/RISE  && \
- cd /home/RISE && \
- git checkout dev && \
- yarn install && \
- yarn run build && \
- pip install -e . && \
- jupyter server extension enable rise && \
- jupyter serverextension enable rise && \
- jupyter labextension develop --overwrite . && \
- jupyter-nbextension install rise --py --sys-prefix --symlink && \
- jupyter-nbextension enable rise --py --sys-prefix && \
- rm -rf /tmp/yarn* /tmp/nodejs* /tmp/npm* /tmp/v8* && \
- cd -
+# RUN cd /home/RISE && jupyter server extension enable rise && \
+#    jupyter serverextension enable rise && \
+#    jupyter labextension develop --overwrite . && \
+#    jupyter-nbextension install rise --py --sys-prefix --symlink && \
+#    jupyter-nbextension enable rise --py --sys-prefix && \
+#    rm -rf /tmp/yarn* /tmp/nodejs* /tmp/npm* /tmp/v8*
 
 USER root
-RUN fix-permissions "/home/RISE"
 
-# done with custom install of RISE for lab
+# Commenting out for now, duplicate from stage 1
+# RUN dpkg --add-architecture i386 && \
+#     apt-get -y update --fix-missing && \
+#     apt-get -y install ${ADDITIONAL_DISTRO_PACKAGES} && \
+#     apt-get clean && rm -rf /var/lib/apt/lists/*
+
+# we want the container to feel more like a fully fledged system so we are pulling the trigger and unminimizing it
+# RUN [[ $UNMIN == "yes" ]] &&  yes | unminimize || true
+
+
+# Add ARM development environtment
+# COPY aarch64vm /home/aarch64vm
+
+# final bits of cleanup
+# RUN touch /home/${NB_USER}/.hushlogin && \
+# # use a short prompt to improve default behaviour in presentations
+#     echo "export PS1='\$ '" >> /home/${NB_USER}/.bashrc && \
+# # work around bug when term is xterm and emacs runs in xterm.js -- causes escape characters in file
+#     echo "export TERM=linux" >> /home/${NB_USER}/.bashrc && \
+# # finally remove default working directory from joyvan home
+#     rmdir /home/${NB_USER}/work
 
 # one more fix permissions for good measure ;-)
 RUN  fix-permissions "${CONDA_DIR}" && \
-     fix-permissions "/home/${NB_USER}"
-     
+     fix-permissions "/home/${NB_USER}" 
+     # && \
+     # fix-permissions "/home/RISE" && \
+     # fix-permissions /home/aarch64vm
+
 # as per the nbstripout readme we setup nbstripout be always be used for the joyvan user for all repos
 RUN nbstripout --install --system 
 
@@ -170,7 +223,7 @@ ARG OPE_GROUP
 ARG CHOWN_HOME=yes
 ARG CHOWN_HOME_OPTS="-R"
 ARG CHOWN_EXTRA_OPTS='-R'
-ARG CHOWN_EXTRA="/home/aarch64vm /home/RISE ${CONDA_DIR}"
+ARG CHOWN_EXTRA="${CONDA_DIR}"
 ENV OPE_UID=${OPE_UID}
 ARG NB_UID=${OPE_UID}
 ENV NB_UID=${NB_UID}
@@ -196,18 +249,8 @@ RUN /usr/local/bin/start.sh true; \
 # an opportunity to set things up based on dynamic facts such as user name
 COPY start-notebook.d /usr/local/bin/start-notebook.d
 
-# over ride locale environment variables that have been set before us
-ENV LC_ALL C.UTF-8
-ENV LANG C.UTF-8
-ENV LANGUAGE=
 ENV USER=$NB_USER
-
-# current rhods openshift does not honor set group execution bit
-# as such /usr/games/moria cannot write to /var/games/moria/scores.dat
-# so we are changing the group ownership of /var/games/moria/scores.dat
-# to users which allows jovyan to write to it .. not ideal but a
-# fix
-RUN chgrp users /var/games/moria/scores.dat
 RUN chgrp root -R /home
 USER $NB_USER
 CMD  ["/bin/bash", "-c", "cd /home/jovyan ; start-notebook.sh"]
+
