clean up and finalize the checksum test

diff --git a/.github/workflows/checksum_test.yaml b/.github/workflows/checksum_test.yaml
--- a/.github/workflows/checksum_test.yaml
+++ b/.github/workflows/checksum_test.yaml
@@ -18,12 +18,26 @@ jobs:
       - name: Pull the most recent image
         run: |
           make pull-priv
-      - name: Get checksum value
+      - name: Compare checksum value #creates var with checksum value to be compared 
         run: |
-          make checksum | sha256sum
-      - name: Run inputs diff #creates var with checksum value to be compared 
-        run: |
-          make checksum > checksum_runner.txt
-          diff checksum_runner.txt checksum_local.txt
-
+          echo "Getting the image checksum"
+          PERMISSIONS_CHECKSUM=$( make checksum )
+          QUICK_TRIM=${PERMISSIONS_CHECKSUM::64} #quick_trim is used to get rid of the tailing "-" after the checksum
+          echo "Comparing the correct checksum value"
+          #*********************************************
+          #need to insert correct image CHECKSUM val to compare
+          #*********************************************
+          CHECKSUM=8b08390195ad9627e8aa5d8886966b62efa1f553fb72110c2f83d4d7438d8865
+          if [["$QUICK_TRIM == $CHECKSUM"]]; then
+                echo "VERIFICATION COMPLETE"
+                echo "SUCCESS" 
+          else 
+                echo "VERIFICATION COMPLETE"
+                echo "FAILURE"
+                echo "Here is the image checksum:"
+                echo "  $QUICK_TRIM"
+                echo "Here is the correct checksum:"
+                echo "  $CHECKSUM"
+                exit 1
+          fi
           
